data_folder: '/web/data'

excel:
    transaction_date_column: 'C'
    amount_column: 'G'
    description_column: 'H'

categories:
    - supermarkets: ["heijn", "jumbo", "feyter", "lidl", "slagerij", "mercadona", "aldi", "supermercado"]
    - eat-outside: ["bedrijfsrest", "cafetaria", "hoek", "frituur"]
    - transport: ["picobello", "gabriels"]
    - fast-food: ["domino's", "mcdonald's", "amigo"]
    - shopping: ["hema", "kruidvat", "gamma", "ikea", "action", "premaman", "blokker"]
    #- fix-costs: ["sabewa", "gemeente", "viveria", "doorlopend", "delta", "zeelandnet", "walstraat"]